### ISSUE TITLE
Dynamically add markers without full rerender

### ISSUE THREAD

**Issue by jarredt** [chrisrzhou/react-globe#11]
It would be really powerful to be able to dynamically add or remove markers without causing a full re-render. This would enable finer-grain control of marker render sequencing/order, and open up use cases for dynamically adding markers from remote data fetched at an interval.

Perhaps markers could be their own components that are children of the Globe, so mounting/unmounting them would add/remove from the globe?

**Comment by chrisrzhou** [comment]
Hey @jarredt, this is a great suggestion.  This probably cannot be done via React since the rendering logic is in threejs.  We could adopt the D3 add/remove/update pattern to approach this.  It might not be easy to implement but I think there could be a way.  Can I check the following behavior?

- Given the existing set of markers, the globe behaves correctly and smoothly (click/hover effects don't reset).
- When markers are added/removed/updated when `markers` props is updated with a new array, it should not reset the animation of the globe and markers and should just add/remove/update the markers respectively?

**Comment by jarredt** [comment]
Correct -- my particular use case would be fetching batches of coordinates from a remote server at an interval (say every 30 seconds). For each fetch, I'd like to add markers at those coordinates to the existing markers without any visual disruption to the globe/existing markers.

So ideally, the visual behavior would be the user sees the existing markers, and then the new markers render -- but the globe doesn't re-render or restart animation, and the existing markers don't re-render or restart animation.

**Comment by chrisrzhou** [comment]
Nice, thanks for confirming.  I might not have time to look into this anytime soon, but I have a feeling it can be done easily by rewriting some of the code in `useMarkers.ts` to using the  `selection.join(enter, update, exit)` pattern in `d3`.  I recently used this pattern when working on [something else](https://github.com/chrisrzhou/react-wordcloud/blob/master/src/render.ts#L36).  Hopefully it is just that simple!

I'm keeping this issue open because I definitely think it is important and valuable to have this functionality for a smooth experience.  I won't be able to get to it within the next month, but if you want to take a jab let me know.

**Comment by jarredt** [comment]
Right on. For now I'll probably use 'resium' library for my prototyping.
Not sure I'll be able to dig in to attempt a changeset here but I'll let
you know if I do!

**Comment by jjwallace** [comment]
I would also love this feature, maybe I will take a hack at it.

**Comment by shahruz** [comment]
@chrisrzhou Related to this: is there any way to pause the auto-rotation without a full re-render? I know it can be done internally (when focusing on a marker for example), but passing in a new cameraOptions prop seems to re-render instead of pausing in place. I tried adjusting the autoRotate bool as well as setting autoRotateSpeed to 0.

**Comment by chrisrzhou** [comment]
I'm going to spend the week looking into these features.  I think they are useful and valuable enough to try to implement.  Will provide an update once I can see how to scope this out correctly!

**Comment by jjwallace** [comment]
> I'm going to spend the week looking into these features. I think they are useful and valuable enough to try to implement. Will provide an update once I can see how to scope this out correctly!

Has any updates occurred with the issue of stoping map marker refresh?

**Comment by chrisrzhou** [comment]
Hi @jjwallace! I've been really busy the past month so I couldn't see this through, but hoping to get this done within two weeks on my spare time!  I am working on refactoring the internals so that this can be supported!  There is quite a bit of refactoring to get this to work, and resolve other re-rendering bugs.

The goals for the next version will be:
- Better control of globe without re-rendering on various prop changes (e.g. options, markers, callbacks).
- Take the approach of [Mike Bostock's General Update Pattern](https://bl.ocks.org/mbostock/3808234) when transitioning new/updated/removed markers.
- Update docs with examples that demonstrate updating markers.
- Potentially expose and export a consolidated `Globe` JS class for users who wish to just use the `GlobeManager` class to build globes and either skip React entirely, or just manage their own `GlobeManager` instances in their React components.

It's going to be quite a meaty change, but I feel it's important to ship these features because they add much improved usability for building globe projects!

**Comment by chrisrzhou** [comment]
Making good progress on this.  A new version should be available soon in the next few days!  Just finishing up on debugging a few issues and updating the docs.  Can't wait to ship this out to you guys!

**Comment by jjwallace** [comment]
Very exciting, cannot wait :) 👍

**Comment by jjwallace** [comment]
<img width="264" alt="Screen Shot 2019-10-18 at 2 21 08 PM" src="https://user-images.githubusercontent.com/4450959/67129154-a36fda00-f1b2-11e9-96d1-2c0af243510e.png">

PNG Sprite Markers have some alpha masking issues with rendering over the geometry glow... See image screenshot....

Also anyone doing the upgrade don't forget to update three library due to changes with orbital controls.  Here is a link https://discourse.threejs.org/t/recent-change-to-orbitcontrols-breaks-some-projects/8780

**Comment by chrisrzhou** [comment]
Cool to see how everyone is using custom renderers! I'm not very knowledgeable on sprites or using custom marker renderers.  Can you try turning off the globe glow and see if the problem still exists?  Will an image with transparent background fix the issue as well?

**Comment by chrisrzhou** [comment]
Closing issue since the feature has been shipped and most questions are addressed!
