### ISSUE TITLE
Alternative textures - political map

### ISSUE THREAD

**Issue by delaudio** [chrisrzhou/react-globe#12]
Hi, I'd like to set alternative textures, in particular I'd like to try some visualizations with a political map, instead of a topographic map. Can I ask you where you found these textures? Thank you.

**Comment by chrisrzhou** [comment]
Hi, I found my textures throughout Google image search.  They are stored in the `textures` folder in this repo.

In general, if you refer the globe texture to a valid image data file or URL, it will work.  If it is a URL, make sure the endpoint supports cross-origin.  If you upload to your own Github, you can refer it it using `raw.githubusercontent.com/USER_NAME/REPO_NAME/PATH_TO_IMAGE`.  Here's an example [Codesandbox](https://codesandbox.io/s/react-globe-basic-oxd3y) with a [test image](https://raw.githubusercontent.com/chrisrzhou/test-image/master/political-world-map-hd.jpg).

Picking a good quality image is important, and in general, the image should use a standardized projection since `three` is mapping the texture from 2D to a sphere.

**Comment by delaudio** [comment]
Thank you! Yes, I checked the folder and codesandbox but since the three part was not fully clear to me I was thinking about maybe it would have been about a specific kind of projection with a particular ratio between height and weight. I'll try. Thank you! :)

**Comment by chrisrzhou** [comment]
resolved
