### ISSUE TITLE
Is it possible to get (visible) Marker x and y for annotation?

### ISSUE THREAD

**Issue by jjwallace** [chrisrzhou/react-globe#13]
![image](https://user-images.githubusercontent.com/4450959/60304921-b43ccd00-98ef-11e9-8375-24a40134746e.png)

Is it possible to get visible marker (window) x and y locations to draw annotations?  From what im looking at this is collected with the mouse x and y for tooltip.  It would be really neat to have labels or tool tips active all the time.  I would like to look into this and build a prototype, which direction do I go?

**Comment by chrisrzhou** [comment]
Hi @jjwallace, currently this is not supported and might not be easy to accomplish since the event data is captured on various events that `three.interaction` library supports.  Theoretically, if we hold all the three marker objects in memory, we can keep track of the three objects and expose them with an `onAnimate` callback in the component prop that captures this everytime `requestAnimationFrame` runs.

 I'm a little hesitant going with this approach.  There's another way to accomplish this if you would like.  If you would like to render annotations to the globe, you can implement a custom `markerOptions.renderer` that renders a Three object to the marker.  Doing this is slightly beneficial for now since there would be no need to introduce code complexity to the project, and you can rely on `react-globe` to position and render the custom marker (with annotation) on the globe.

Let me know if this works, and sorry for the delayed response!

**Comment by jjwallace** [comment]
Wow that might be pretty neat.  I will take a look at that approach.  Thank you for the reply.
