### ISSUE TITLE
Clicking marker does not respect focusOptions

### ISSUE THREAD

**Issue by kshahani** [chrisrzhou/react-globe#16]
Looks like we need to pass in the current focus options here:
https://github.com/chrisrzhou/react-globe/blob/b4861ef89d0717051af81753f279ba846150df3f/src/Globe.ts#L652

**Comment by chrisrzhou** [comment]
Hey @kshahani , this is now fixed in `v5.0.0`.

Note that `v5.0.0` introduces a couple of breaking changes so check the `changelog.md` or Github release if you want to upgrade to it!  There's a couple of bugfixes, improved/flatter props, improved documentations, better support for `Globe` class, and overall a simplified implementation.
