### ISSUE TITLE
Sprite Group Objects have layer masking issues with translucent / alpha layers

### ISSUE THREAD

**Issue by jjwallace** [chrisrzhou/react-globe#18]
![asdf](https://user-images.githubusercontent.com/4450959/71701592-54801c80-2d7f-11ea-83d1-f8a39efb21ef.png)
When using sprites and text in groups for markers we get clipping of the globe glow and also other sprite / group objects.  How can this be solved?  I was thinking a separate render object might help?  I understand that sprites are rendered last but how do we see alpha bounding box over-lapses from sprite effecting sprite?

**Comment by chrisrzhou** [comment]
I think this is beyond the scope of what I can help, but reasoning about the problem seems that:
- The `globeGlow` is an object that sits above the globe (z-axis)
- Any objects placed in specific z-values could easily appear below or above the glow.

There is not an easy way to generically solve the problem so I recommend turning off the `glow` effects for your use case.

We can potentially set some opacity for the glow, so things still show, but this amount of customization is probably too advanced for this library, and writing a custom one might be more effective!
