### ISSUE TITLE
Texture Not Staying Applied

### ISSUE THREAD

**Issue by t2** [chrisrzhou/react-globe#20]
When setting the Globe to dark mode it shows dark mode initially but then jumps back regular view. This happens in the demo as well https://codesandbox.io/s/knhlr.

**Comment by jjwallace** [comment]
I wonder if this is due to it being hosted on github, maybe there is a hosting limit that limits http calls from the same IP?  The first time i loaded it it worked, then every time after that it failed.  

Load from another host perhaps? 

Interesting...

**Comment by t2** [comment]
I moved to a custom map hosted on AWS. Works fine. Must be like you said.

**Comment by gmmakqa** [comment]
Hello! I think this is still an issue. I notice that the defaultGlobeOptions uses an image hosted on Github. I'm using a small image on localhost which loads very quickly. If the default texture takes longer to load than my texture (specified in globeOptions) the default will end up overriding my setting.

**Comment by t2** [comment]
@gmmakqa I had to revert to 3.0.0 because I was seeing the same on 4.0.0. So, yes, still an issue.

**Comment by madkarlsson** [comment]
Can confirm that this is an issue but to expand:

There seems to be something off with the props overriding the default options. Not only the texture loading, which seems to somewhat randomly load in different orders but in all cases, the default texture gets loaded. Either before the texture, we assign or replaces our texture. There is a visible flicker between them. I've even delayed the globe rendering until both textures are loaded, same behaviour, so I don't think it has anything to do with network speeds fetching the textures.

Also had problems with "enableGlow". Setting it to `false` _does still_ render a glow, but the default one so efficiently I can't disable glow without modifying the values to make it really, really small.

Reverting back to 3.1.1 solved the issues.

**Comment by gmmakqa** [comment]
I fixed this in my own fork by changing:

new TextureLoader().load(texture, map => { })

to 

let map = new TextureLoader().load(texture);

in src/Globe.ts.

So instead of waiting for the texture to load and using the callback - which causes the race issue between large/slow loading remote images and smaller/local ones - we can make use of the fact that TextureLoader.load() returns a texture object which can be used to make the material immediately, so the custom props override the default properly. This solves the original issue, and it might also solve the glow issue as the glow is also set up in the texture load callback.

**Comment by madkarlsson** [comment]
@gmmakqa Nice. I'm fine with staying on 3.1.1 as for now but I'm sure @chrisrzhou would appreciate a PR

**Comment by chrisrzhou** [comment]
Hey guys, I've been super busy with other work, but going to revisit this on the weekend.  Thanks for exploring fixes and giving me some repro.

**Comment by chrisrzhou** [comment]
Hey everyone, this is now fixed in `v5.0.0`.  The issue was `v4.0.0` did not allow a way to set this on the initialization of the globe, and only when updates to the `*options` props are made.

In `v5.0.0`, some of these props now play a role in the initialization of the globe.  In addition, you should be able to just assign `globeTexture`, `globeBackgroundTexture`, and `globeCloudsTexture` and this should load the visualization up without a re-render/flicker.  The documentation in https://react-globe.netlify.app/usage/textures should give you an example of how you can wire up relevant callbacks to wait for the textures to load.

Note that `v5.0.0` introduces a couple of breaking changes so check the `changelog.md` or Github release if you want to upgrade to it!  There's a couple of bugfixes, improved/flatter props, improved documentations, better support for `Globe` class, and overall a simplified implementation.
