### ISSUE TITLE
Animate on new item, Custom Marker Render.

### ISSUE THREAD

**Issue by jjwallace** [chrisrzhou/react-globe#21]
I am dynamically adding items from a socket connection.

When a new marker item is added I navigate on a tour to the location of that marker item.

On each custom marker there is an animation.

```
var group = new THREE.Group();
item.add(group);
var myAnimation = new TimelineMax({repeat: 0});
myAnimation.delay(1);
myAnimation.to(group.position, 2, { z: 0, ease:Power2.easeInOut});
myAnimation.to(group.scale, 2, { x: 1, y: 1, z: 1 });
```

This animation does not play when the new item is added, however when the globe initializes all the markers play the animation.  How can I get a callback on new Marker add?

**Comment by chrisrzhou** [comment]
I don't have enough context from what you have provided, but the lib exports a named method called `tween` that you can use.

`tween` is used in the `render` method that is called in `requestAnimationFrame`, so any animations that uses it should be updated in the main Globe's animation cycle: https://github.com/chrisrzhou/react-globe/blob/master/src/Globe.ts#L224-L227

You can also do something without the method exported by the library in https://codesandbox.io/s/knhlr.  I think a drawback of not using the main rendering cycles is creating new `requestAnimationFrames` that could have performance issues.

I think better support to allowing the component to accept `renderers` (callback) so that it can apply them in the main `render` cycle would be more ideal.
