### ISSUE TITLE
enableDefocus not working

### ISSUE THREAD

**Issue by a760109** [chrisrzhou/react-globe#30]
Hi 
I went to disable defouces  but not working.

const markers = [
    {
        id: 1,
        city: 'Singapore',
        color: 'red',
        coordinates: [1.3521, 103.8198],
        value: 50,
    },
];

<ReactGlobe
        markers={markers}
        focusOptions={{enableDefocus: false}}
        globeOptions={{
          texture:
            'https://raw.githubusercontent.com/chrisrzhou/react-globe/main/textures/globe_dark.jpg',
        }} 
 />

**Comment by chrisrzhou** [comment]
Hey I'll be taking a look at the repo and going over bugs and improving some stability in `v5`.  Will probably take 1-2 weeks to get everything updated and in place.  Will address this in the release!

**Comment by chrisrzhou** [comment]
`v5.0.0` is just released and this bug is addressed.  You can test the behavior by checking the second example in this page: https://react-globe.netlify.app/usage/focus where `enableDefocus` is set to `false`.

`v5.0.0` introduces some breaking changes, so if you intend to upgrade to it, please refer to the `changelog.md` or Github release notes for details.  In general, the props are simplified/flatter and renamed.
