### ISSUE TITLE
404 on get image from raw.githubusercontent

### ISSUE THREAD

**Issue by DelahayesTheo** [chrisrzhou/react-globe#31]
![image](https://user-images.githubusercontent.com/22497806/88664178-f630d780-d0dc-11ea-9c40-97bcdf3e92d2.png)

It seems like the images are not available for threejs to use. It results into a blank page instead of the globe itself.

I tested it locally and the examples in the website via codepen are also crashing.

Might have to do with the master/slave controversy and the change of *master* to *main*
Ressources are there at https://raw.githubusercontent.com/chrisrzhou/react-globe/main/textures/globe.jpg

**Comment by DelahayesTheo** [comment]
It was because of absolute path refering to master instead of the newly named branch "main".

Here's a pull request that changes the master refences to main :
https://github.com/chrisrzhou/react-globe/pull/32

**Comment by chrisrzhou** [comment]
Hi @DelahayesTheo, you are absolutely right that this was due to the recent branch changes from `master` to `main`.  I'm making some work in `v5` to improve a few things, and to remove/decouple image assets being served by the package.

Until then, anyone encountering the issue should try to reference `main/textures/*` assets, but when the project is updated to `v5`, these assets will be removed and the default textures will fail to load.  The better recommendation would be to supply your own assets.  In general, the package should work without external dependencies to assets fetched over the network as many possible things could go wrong:
- Files updated/deleted/renamed (as in the current scenario).
- Network issues to `https://raw.githubusercontent.com`.
- Future auth requirements to `https://raw.githubusercontent.com`.

Expected `v5` changes:
- Decoupling/removal of texture assets.
- Decoupling tooltip/tippy CSS.
- Support various builds (ESM, CJS, UMD etc)
- Updated TS types.
- Updated docs to suggest alternatives while still ensuring component is easy to use and wire up.
- Internal implementation probably significantly refactored **but** keeping component props API largely unchanged.

**Comment by esteban199** [comment]
i have the same issue

**Comment by chrisrzhou** [comment]
Hey everyone,

`v5.0.0` was just released.  I decided to keep the `/textures` folder to make it convenient for people to have a default asset bootstrapped and see the globe visualization immediately.  I did  make a note about how this is not a good practice for reasons explained in the issue but will leave it up to implementors to address:
https://react-globe.netlify.app/faq#globe-textures

Note that `v5.0.0` introduces a couple of breaking changes so check the `changelog.md` or Github release if you want to upgrade to it!  There's a couple of bugfixes, improved/flatter props, improved documentations, better support for `Globe` class, and overall a simplified implementation.
