### ISSUE TITLE
Better explanation of point light

### ISSUE THREAD

**Issue by haveamission** [chrisrzhou/react-globe#35]
I have just a basic example of point light, like this:

```
<ReactGlobe
  options={{
    pointLightColor: 'white',
    pointLightIntensity: 1,
    pointLightPositionRadiusScales: [-1, 0, -1],
  }}
/>
```

However I'm not sure what the pointLightPositionRadiusScales are.

I want to make a globe where the center of it is highlighted, but the sides are a bit darker, as if the viewer were the "sun" so to speak, but I am not quite sure how to do that, and the docs are a little light on explanation.

**Comment by chrisrzhou** [comment]
Try these options:

```js
    ambientLightIntensity: 0.5,
    pointLightColor: 'white',
    pointLightIntensity: 2,
    pointLightPositionRadiusScales: [0, 0, -1.5],
```

I'll be honest with you, I don't completely know how the math/physics of the point light works, but the code of `pointLightPositionRadiusScales` is used to position the `x, y, z` of the point light (which is attached to the `camera`): https://github.com/chrisrzhou/react-globe/blob/main/lib/lights.js#L34

Everything in the project is measured in `radiusScale` (the globe has a hardcoded radius that users should not need to know), so placing things is gauged using this unit measurement.  `0` for `x`, and `y` values in the above example means the light is actually placed in the core of the earth, but for the `z` value, we're placing it in the negative z-direction at a distance `1.5` times the radius of the globe.  I guess the z-axis is the axis where we are looking at the globe directly and negative z-direction is the direction from which we look at.

To achieve your effect, I lowered the `ambientLightIntensity` to make the `pointLightIntensity` more pronounced.

And yes, 100% agree this can be better documented, I think I've just really quickly documented various features with code playgrounds but I appreciate the feedback and can probably elaborate it more in a future docs update.

Hope this answers your question!

**Comment by haveamission** [comment]
Thanks, those values didn't work exactly for me, but similar ones did. Though the globe is very dark on zoom in.

**Comment by chrisrzhou** [comment]
@haveamission, I think I managed to understand the behaviors of the light options (despite this being my own project!).  It was more clear to me when I coded it in the past.  I'll document this more based on your feedback, but this is how it roughly behaves:

- ambient light illuminates the scene without a source and applies the light everywhere (straightforward).
- point light is a source of light from a specified point.  The light (in the code's implementation) is attached to the camera and is specified by `[x, y, z]` coordinates.
- lights are 'off' if their intensities are `0`

The coordinate system seems to be

```
        y
        |
        |
        G - - - x
       /
      /
     z (facing you)
```

With this in mind, we can reason why positive/negative values of lights behave.

The examples I gave you above was actually a bad configuration but it makes sense if we understand the rules above now:

```js
{
    ambientLightIntensity: 0.5,
    pointLightColor: 'white',
    pointLightIntensity: 2,
    pointLightPositionRadiusScales: [0, 0, -1.5]
}
```

This example places an ambient light with `0.5` intensity, and a point light directly **behind** the globe.  The globe is dark at some zoom distance because if you zoomed in too close, you would not see the point light source.  At this point, the 'dark' globe is illuminated by the ambient light source with its specified intensity.  In fact, if you set the ambient light source value to `0`, the globe disappears!  This is intuitive to real life if you moved too close to a globe (in a museum) that was only illuminated with a light source from behind, moving too close, you would see no light emanating at all, and you would see nothing.

With this behavior now explained, we can look at your example.  If you want to illuminate a globe the way you described (bright at the center and dark on the edges), you are looking to:
- lower the ambient light so most light contrast is achieved through the point light.  The less ambient light, the more effective the point light illumination is.
- Place the light as close to the globe but avoid negative values (which will cause the cutting out of light as you noticed above).

Here's the suggested configuration:
```js
{
    ambientLightIntensity: 0,
    pointLightColor: 'white',
    pointLightIntensity: 2,
    pointLightPositionRadiusScales: [0, 0, 0]
}
```

Losing the ambient light makes this effect more pronounced.  The light is placed directly at the center of the globe (the globe's core).  `three` physics isn't real physics, but the idea is the light now emanates from that and spreads out radially.  The `three` point light also does not seem to decay, so the further it is placed out, does not actually diminish the intensity over the distance.  In this case, putting it as close to the globe is analgous to pointing a light on a sphere so the light radius will illuminate only parts of the globe.

Outside of this, I don't think I was able to reason and find a configuration that can make this even more pronounced.  To make this work, we would probably need to customize the light source, which is not made available in the library at this time of writing.

Hope this explanation helps and I'll document this more briefly in the docs soon.

**Comment by chrisrzhou** [comment]
At some point, I had an ambitious plan to wire up a UI for `react-globe` that will allow an interface to configure the globe through sliders  and inputs.  I don't have to the time to do that, but that would make understanding globe options much more intuitive and exploratory.  I may get back to that at some point in the future, but not betting on it :P
