### ISSUE TITLE
onWheel event not triggering

### ISSUE THREAD

**Issue by aboe026** [chrisrzhou/react-globe#8]
I'm trying to detect a wheel scroll for when a user zooms in or out of the globe. I attempt to do this on a div containing the globe, but for some reason the zoomHandler method does not get called. Here's my code:
```
<div
  onMouseDown={this.handleDragStart}
  onTouchStart={this.handleDragStart}
  onMouseUp={this.handleDragEnd}
  onTouchEnd={this.handleDragEnd}
  onWheel={this.handleWheel}
  className={classNames('full-width', 'full-height')}
>
  <ReactGlobe
    globeOptions={{
      enableBackground: true,
      cloudsSpeed: 0.125,
      enableClouds: true
    }}
    cameraOptions={{
      maxDistanceRadiusScale: 10,
      distanceRadiusScale: continent ? this.getZoom() : (width === 'xs' ? 5 : 3),
      enableAutoRotate: false
    }}
    lookAt={this.getFocus()}
    markers={visits.map((visit) => {
      return {
        visit: visit,
        value: 1,
        color: 'red',
        coordinates: [ visit.lat, visit.lon ]
      }
    })}
    markerOptions={{
      activeScale: 1.3,
      animationDuration: 1000,
      enableGlow: true,
      enableTooltip: true,
      glowCoefficient: 0,
      glowPower: 3,
      glowRadiusScale: 2,
      radiusScaleRange: [0.005, 0.02],
      type: 'bar',
      getTooltipContent: marker => `${marker.visit.city}, ${marker.visit.state}`,
    }}
    onClickMarker={(marker, markerObject, event) => fullscreen(marker.visit)}
  />
</div>
```
Capturing other events (such as `onMouseDown`, `onTouchStart`) seem to work fine. I'm not sure why the `onWheel` event isn't getting properly triggered.

**Comment by chrisrzhou** [comment]
Not all events are implemented in `react-globe`.  Only the mousedown, mouseover events are bound to `three.interaction`.  I can check if we can add `onwheel` event and tag you on a PR.

**Comment by chrisrzhou** [comment]
Hi @aboe026, I took a look at `three-orbitcontrols`, `three.interaction`, and I don't think that these dependencies expose any useful methods that help to implement this in an easy way.  An approach to doing this is to expose an `onWheel` prop handler that can be passed down to the `div` node containing the `canvas` in `react-globe`, as you have tried in your example.

However this still won't work because the `canvas` element sits on top of the `div`.  There are no real DOM events on the `canvas` elements so even though the `div` wraps the `canvas` element, the `canvas` element is rendered on top of it, so it can't be accessed.  You can put the `div` element above the `canvas` by controlling the `z-index`, but doing so could create other problems when using this component.

For the scope of this component, I'm probably not inclined to add and work on this feature.  It's also a little challenging because zooming on the globe can be caused by other interactions (e.g. `scroll`, and not necessary `wheel` events).

Sorry for the inconvenience and hope you understand! Let me know if you come up with a good solution outside of this component!
